# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FBChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FBChat
  pod 'Firebase/Core'
  pod 'Firebase/Auth’
  pod 'Firebase/Firestore’

  # Comment the next line to avoid duplicated files providing 'react-native' module
  # pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end
